package com.example.greengiant.canopy2;

/**
 * Created by Justin on 4/12/2016.
 */

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "Voltage_Readings")
public class VoltageReading {
    private int id;
    private String shade_id;
    private String timestamp;
    private int voltage;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public int getId(){
        return id;
    }

    public void setId(int id){
        this.id = id;
    }

    @DynamoDBHashKey(attributeName = "Shade_Id")
    @DynamoDBAutoGeneratedKey
    public String getShade_id(){
        return shade_id;
    }

    public void setShade_id(String shade_id){
        this.shade_id = shade_id;
    }

    @DynamoDBHashKey(attributeName = "Timestamp")
    @DynamoDBAutoGeneratedKey
    public String getTimestamp(){
        return timestamp;
    }
    public long getTimestampAsLong(){
        return Long.valueOf(timestamp).longValue();
    }

    public void setTimestamp(String timestamp){
        this.timestamp = timestamp;
    }

    @DynamoDBHashKey(attributeName = "Voltage")
    @DynamoDBAutoGeneratedKey
    public int getVoltage(){
        return voltage;
    }

    public void setVoltage(int voltage){
        this.voltage = voltage;
    }

}
